import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className="grid h-screen place-content-center ">
      <Head>
        <title>Instep</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-center">
        <h1 className="text-xl font-bold my-4">Instep</h1>
        <div className="flex row">
            <Link href="/apply-now" >
              <button>Apply</button>
              {/* <a href="" className="px-5 py-2  bg-black text-white rounded" >Apply</a> */}
            </Link>
          <Link href="/applications" >
            <button>Show Applications</button>
          </Link>
        </div>
      </main>
    </div>
  );
};

export default Home;
